apiVersion : apps/v1
kind : Deployment
metadata:
  name : soul-deployment
  labels:
    app : httpd
spec:
  template:
    metadata:
      labels:
        app : httpd
    spec:
      containers:
        - name : soul
          image : devtechieops/soul:1.0
          ports:
            - containerPort : 80
  selector:
    matchLabels:
      app : httpd
